name: Build latest data (Top5)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * 1-5"
permissions:
  contents: write
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run fetch_top5.py
        env:
          GAS_ENDPOINT: "https://script.google.com/macros/s/AKfycbwACq7RUHXNYDv6Qod_mSGjhzSIjatJZz4_2h-Lw5aRkuwSlIeAIJqlPQuxxrBnlsVGGw/exec"
        run: |
          python fetch_top5.py
          git status --porcelain || true
      - name: Commit & push if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data snapshots
            git commit -m "chore: update latest.json and snapshot [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
