name: Fetch Selected Stocks Daily

on:
  schedule:
    - cron: "0 14 * * *"   # 매일 오전 9시 EST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install yfinance pandas

      - name: Fetch selected stocks
        run: python fetch_selected_stocks.py

      - name: Commit & push data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "daily update $(date -u +'%Y-%m-%dT%H:%MZ')" || echo "No changes"
          git push
